config/routes.rb
Rails.application.routes.draw do
  get 'stock/index'
  get 'stock/:id', to: 'stock#draw', as:'draw'
  root 'stock#index'

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  validates_uniqueness_of :symbol


  def self.search(search)
    unless search.blank?
      where("name LIKE ?", "%#{search}%") + where("symbol LIKE ?", "%#{search}%")
      # else
      #   Stock.all
    end
  end

  def format_data
    data_arr = Array.new
    # data_arr << ['Date','Price']
    begin
      data_open_struct = get_data
    rescue
      return false
    end
    data_open_struct.each do |single_day|
      # single_day.trade_date.slice!(0..4)
      data_arr << [single_day.trade_date, 0.25*(single_day.open.to_f+single_day.close.to_f+single_day.high.to_f+single_day.low.to_f)]
    end
    data_arr
  end

  private

  def get_data
    yahoo_client ||= YahooFinance::Client.new
    yahoo_client.historical_quotes(self.symbol, {raw: false, start_date: Time::now-(24*60*60*30), end_date: Time::now}) # 30 days worth of data
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stock_controller.rb
class StockController < ApplicationController

  def index
    if params[:search]==""
      @empty_query = true
    elsif params[:search].nil?
      @start = true
    else
      @query_str = params[:search].gsub(/\W+/, '')
      @searched = Stock.search(@query_str)
      unless @searched.nil?
        @count = @searched.uniq{|x| x.symbol}.size
        @searched = (@searched.uniq{|x| x.symbol} .sort_by &:name).paginate(:page => params[:page], :per_page => 20)
      end
    end
  end

  def draw
    @stock = Stock.find_by_id params[:id]
    @draw_data = @stock.format_data
    # @test_data = @draw_data.to_s
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Stocks" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag "stock" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="main">
    <div class="container">
    <%= yield %>
</div>
    </div>
  </body>
</html>

app/views/stock/_chart.erb
<div class="row">
  <div id="line-chart" style="height: 500px;">
    <%= line_chart Stock.group(:created_at).count %>
  </div>
</div>

app/views/stock/_list.html.erb
<table>

  <tr>
    <th>Symbol </th>
    <th>| Name </th>
    <th>
  </tr>

  <% @searched.each do |s| %>
      <tr>
        <td><%= highlight s.symbol, @query_str %></td>
        <td><%= highlight s.name, @query_str %></td>
        <td>
          <% unless s.symbol.include? '^' %>
          <%= link_to "Show Chart", draw_path(s.id), :class => 'chart'%>
              <% else %>
              Sorry, Preferred Stock is not Supported
              <% end %>
          <%#= link_to "Show Chart", draw_url(s.id), :class => 'chart',:remote => true, data: {:'reveal_id' => "stock-#{s.id}", :"reveal-ajax" => true}%>
          <!--<div id="stock-<%#= s.id %>" class="reveal-modal" data-reveal>-->
            <%#= render 'stock/draw', stock: s%>
            <!--<a class="close-reveal-modal">&#215;</a>-->
          <!--</div>-->
        </td>

  <% end %>
</table>

<%#= javascript_tag do%>
    <!--$(document).on('click', '.chart', function () {-->
    <!--var id = $(this).attr('data-reveal-id');-->
    <!--$('#' + id).foundation('open');-->
    <!--});-->


    <!--$(document).on('click', '.close-reveal-modal', function () {-->

    <!--$(this).parent().foundation('reveal', 'close');-->
    <!--});-->
<%# end%>

app/views/stock/draw.html.erb
<div id="stock-<%= @stock.id %>">

  <div class="row">
    <!--<div class="column"></div>-->
    <div class=" small-6  columns small-centered">
      <h2><%= @stock.name %></h2>
    </div>
  </div>
  <%#= @test_data%>
  <% if @draw_data%>
  <div class="row">
    <div class="small-10 columns small-centered" style="height: 520px">
      <%= line_chart @draw_data, :library => {hAxis: {title: 'Time'},
                                              vAxis: {title: 'Price'},
                                              width: 900,
                                              height: 500,
                                              backgroundColor: '#f1f8e9'} %>
    </div>
  </div>
      <% else %>
  <div class="row">
    <div class="small-4 column small-centered">
      Hmmmm....Something weird here.
    </div>
  </div>
      <% end %>


  <div class="row ">
    <div class="small-4 column small-centered">
      <%= link_to "Clear All", '/', :class => 'white_bt', :id => "clear" %>
      <%= link_to 'Back', :back, :class => 'white_bt' %>
    </div>
  </div>
  <%#= render "stock/chart", :stock => @stock %>
  <!--<a class="close-reveal-modal">&#215;</a>-->
</div>

app/views/stock/index.html.erb
<div class="row">
  <div class="small-6 column">
    <h1>Stocks</h1>
  </div>
</div>
<!--<br>-->
<div class="row collapse">
  <div class="small-6 column">
    <%= form_tag stock_index_path, :method => :get do %>
        <div class="row collapse">
          <div class="small-10 columns">
            <%= text_field_tag :search, params[:search], :placeholder => "Stock Symbol or Name" %>
          </div>
          <div class="small-2 column">
            <%= submit_tag "Search", :name => nil, :class => "button" %>
          </div>
        </div>
    <% end %>

  </div>
  <div class="small-6 column">
    <div class="row collapse">
      <div class="small-3 column"><%= link_to "Clear All", '/', :class => 'white_bt button', :id => "clear", :style => '' %></div>
    </div>
  </div>
</div>

<% if @empty_query %>
    <div class="row">
      <div class="small-6 column"><h3>Please input the text to query.</h3></div>
    </div>
<% end %>
<% unless @searched.blank? %>
    <div class="row">
      <div class="large-6 column">
        <h3> <%= @count %> Found</h3>
      </div>
      <div class="large-6 column">
        <h3><%= page_entries_info @searched %></h3>
      </div>
    </div>
    <br>
    <div class="row">
      <%= render 'stock/list' %>
    </div>
    <div class="row">
      <div class="small-6 small-centered columns ">
        <%= will_paginate @searched %></div>
    </div>
<% else %>
    <% unless @start || @empty_query %>
        <div class="row">
          <div class="large-6 column"><h3>Well......Cannot find it.</h3></div>
        </div>
    <% end %>
<% end %>